import { Link } from "wouter";
import { ArrowUpRight, BarChart3, Plus, TrendingUp, UsersRound } from "lucide-react";
import { useGetDashboardSummary, getGetDashboardSummaryQueryKey } from "@workspace/api-client-react";
import { SectionEyebrow, StudentRow } from "@/components/portfolio-ui";

function StatCard({ label, value, detail, tone, icon: Icon }: { label: string; value: string | number; detail: string; tone: "blue" | "teal" | "amber" | "navy"; icon: typeof TrendingUp }) {
  const colors = { blue: "bg-[#e7f0fd] text-[#28629c]", teal: "bg-[#e0f6f1] text-[#237864]", amber: "bg-[#fff3df] text-[#9a671f]", navy: "bg-[#e7eefa] text-[#274a7a]" };
  return <div className="rounded-2xl border border-[#dfe8f0] bg-white p-5 soft-shadow transition-transform hover:-translate-y-0.5"><div className="flex items-start justify-between"><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${colors[tone]}`}><Icon size={18} /></div><span className="font-mono-ui text-[10px] text-[#91a2b5]">LIVE</span></div><p className="mt-5 text-[11px] font-bold uppercase tracking-[.1em] text-[#8091a5]">{label}</p><p className="mt-1 text-3xl font-bold tracking-[-.05em] text-[#203852]" data-testid={`metric-${label.replaceAll(" ", "-").toLowerCase()}`}>{value}</p><p className="mt-1 text-xs text-[#71859e]">{detail}</p></div>;
}

export default function Dashboard() {
  const { data, isLoading, isError, refetch } = useGetDashboardSummary({ query: { queryKey: getGetDashboardSummaryQueryKey() } });
  if (isLoading) return <div className="space-y-8"><div className="h-36 rounded-2xl shimmer" /><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-40 rounded-2xl shimmer" />)}</div><div className="h-80 rounded-2xl shimmer" /></div>;
  if (isError || !data) return <div className="mx-auto mt-12 max-w-md rounded-2xl border border-[#f1d0cb] bg-[#fff7f5] p-8 text-center"><p className="font-mono-ui text-[10px] font-bold uppercase tracking-[.15em] text-[#bd6a5d]">Tidak dapat memuat data</p><h2 className="mt-3 text-xl font-bold text-[#3d4350]">Ringkasan belum tersedia</h2><p className="mt-2 text-sm text-[#7d8794]">Periksa koneksi Anda lalu coba lagi.</p><button type="button" onClick={() => refetch()} className="mt-5 rounded-xl bg-[#1b5a9f] px-4 py-2.5 text-sm font-bold text-white" data-testid="button-retry-dashboard">Coba lagi</button></div>;
  const maxLevel = Math.max(...data.byLevel.map((item) => item.count), 1);
  const maxPeriod = Math.max(...data.byPeriod.map((item) => item.total), 1);
  return <div className="space-y-8">
    <section className="relative overflow-hidden rounded-2xl bg-[#1c4b7e] px-6 py-7 text-white shadow-[0_18px_38px_rgba(28,75,126,.16)] sm:px-8"><div className="absolute -right-16 -top-24 h-64 w-64 rounded-full border border-[#70d6ef]/25" /><div className="absolute right-12 top-8 h-28 w-28 rounded-full border border-[#70d6ef]/20" /><div className="relative flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><SectionEyebrow>Ruang kerja · {new Date().toLocaleDateString("id-ID", { day: "2-digit", month: "long", year: "numeric" })}</SectionEyebrow><h1 className="mt-3 text-3xl font-bold tracking-[-.04em] sm:text-4xl">Selamat pagi, <span className="text-[#71d8ee]">portfolio team.</span></h1><p className="mt-2 max-w-lg text-sm leading-6 text-[#b5cae0]">Pantau progres bahasa dan temukan siswa yang siap melangkah ke partner berikutnya.</p></div><Link href="/admin/students/new" className="relative inline-flex w-fit items-center gap-2 rounded-xl bg-[#f4bf68] px-4 py-3 text-sm font-bold text-[#273d5c] transition-transform hover:-translate-y-0.5" data-testid="link-add-student"><Plus size={17} />Tambah siswa</Link></div></section>
    <section className="grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-4">{[
      { label: "Total siswa", value: data.totalStudents, detail: "di seluruh cohort", tone: "blue" as const, icon: UsersRound },
      { label: "Siap ditempatkan", value: data.readyToPlace, detail: "menunggu matching", tone: "teal" as const, icon: TrendingUp },
      { label: "Sudah ditempatkan", value: data.placedStudents, detail: "partner aktif", tone: "amber" as const, icon: ArrowUpRight },
      { label: "Placement rate", value: `${data.placementRate}%`, detail: "dari total alumni", tone: "navy" as const, icon: BarChart3 },
    ].map((item) => <StatCard key={item.label} {...item} />)}</section>
    <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <section className="overflow-hidden rounded-2xl border border-[#dfe8f0] bg-white soft-shadow"><div className="flex items-center justify-between border-b border-[#e7edf3] px-6 py-5"><div><SectionEyebrow>Pipeline terbaru</SectionEyebrow><h2 className="mt-1 text-lg font-bold tracking-[-.02em] text-[#243b57]">Aktivitas siswa</h2></div><Link href="/students" className="flex items-center gap-1 text-xs font-bold text-[#2464a0] hover:text-[#124d8c]" data-testid="link-view-all-students">Lihat semua <ArrowUpRight size={14} /></Link></div>{data.recentStudents.length ? data.recentStudents.slice(0, 5).map((student) => <StudentRow key={student.id} student={student} />) : <p className="px-6 py-12 text-center text-sm text-[#8193a7]">Belum ada aktivitas siswa.</p>}</section>
      <section className="rounded-2xl border border-[#dfe8f0] bg-white p-6 soft-shadow"><div className="flex items-center justify-between"><div><SectionEyebrow>Komposisi kemampuan</SectionEyebrow><h2 className="mt-1 text-lg font-bold tracking-[-.02em] text-[#243b57]">Level bahasa</h2></div><span className="font-mono-ui text-[10px] text-[#8da0b4]">TOTAL {data.totalStudents}</span></div><div className="mt-7 space-y-5">{data.byLevel.map((item) => <div key={item.level}><div className="mb-2 flex items-center justify-between text-xs"><span className="font-mono-ui font-bold text-[#37627f]">{item.level}</span><span className="font-bold text-[#6e8298]">{item.count} siswa</span></div><div className="h-2 overflow-hidden rounded-full bg-[#edf2f6]"><div className="h-full rounded-full bg-[#318db0] transition-all duration-700" style={{ width: `${(item.count / maxLevel) * 100}%` }} /></div></div>)}</div><div className="mt-8 border-t border-[#e7edf3] pt-5"><div className="mb-3 flex items-center gap-2 text-xs font-bold text-[#73869b]"><BarChart3 size={14} /> Perkembangan cohort</div><div className="flex h-24 items-end gap-2">{data.byPeriod.slice(-6).map((item) => <div key={item.period} className="flex flex-1 flex-col items-center gap-1"><div className="w-full rounded-t-md bg-[#b9e8f1] transition-all hover:bg-[#70d6eb]" style={{ height: `${Math.max(8, (item.total / maxPeriod) * 72)}px` }} title={`${item.period}: ${item.total} siswa`} /><span className="font-mono-ui text-[8px] text-[#94a5b6]">{item.period.slice(-2)}</span></div>)}</div></div></section>
    </div>
  </div>;
}