import { useMemo, useState } from "react";
import { Link } from "wouter";
import { Filter, Plus, RotateCcw, Search, SlidersHorizontal, Users } from "lucide-react";
import { getListStudentsQueryKey, useListStudents, type ListStudentsParams, type StudentLevel, type StudentStatus } from "@workspace/api-client-react";
import { EmptyState, LoadingRows, SectionEyebrow, StudentRow } from "@/components/portfolio-ui";

const levels: Array<StudentLevel | "all"> = ["all", "A1", "A2", "B1", "B2"];
const statuses: Array<StudentStatus | "all"> = ["all", "training", "ready", "placed"];
const statusLabels: Record<string, string> = { all: "Semua status", training: "Dalam pelatihan", ready: "Siap ditempatkan", placed: "Sudah ditempatkan" };

export default function Students() {
  const [search, setSearch] = useState("");
  const [level, setLevel] = useState<StudentLevel | "all">("all");
  const [status, setStatus] = useState<StudentStatus | "all">("all");
  const [showFilters, setShowFilters] = useState(false);
  const params = useMemo<ListStudentsParams>(() => ({ ...(search ? { search } : {}), ...(level !== "all" ? { level } : {}), ...(status !== "all" ? { status } : {}) }), [search, level, status]);
  const { data, isLoading, isError, refetch } = useListStudents(params, { query: { queryKey: getListStudentsQueryKey(params) } });
  const students = data || [];

  return <div className="space-y-7">
    <section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><SectionEyebrow>Direktori privat</SectionEyebrow><h1 className="mt-2 text-3xl font-bold tracking-[-.045em] text-[#213853] sm:text-4xl">Katalog siswa</h1><p className="mt-2 text-sm text-[#73869d]">Cari, saring, dan buka bukti kesiapan setiap siswa.</p></div><Link href="/admin/students/new" className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#1b5a9f] px-4 py-3 text-sm font-bold text-white shadow-[0_8px_16px_rgba(27,90,159,.15)] transition-all hover:-translate-y-0.5 hover:bg-[#154d8b]" data-testid="link-create-portfolio"><Plus size={17} />Buat portofolio</Link></section>
    <section className="rounded-2xl border border-[#dfe8f0] bg-white p-4 soft-shadow sm:p-5"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search size={17} className="absolute left-3.5 top-3.5 text-[#8aa0b7]" /><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari nama, email, atau cohort…" className="h-11 w-full rounded-xl border border-[#d4e1ec] bg-[#fbfdff] pl-10 pr-4 text-sm outline-none transition-colors placeholder:text-[#9eafbf] focus:border-[#4d94ba] focus:ring-4 focus:ring-[#6fd5ee]/15" data-testid="input-search-students" /></div><button type="button" onClick={() => setShowFilters(!showFilters)} className={`inline-flex h-11 items-center justify-center gap-2 rounded-xl border px-4 text-sm font-bold transition-colors ${showFilters ? "border-[#8fc5d9] bg-[#e9f7fa] text-[#21698b]" : "border-[#d4e1ec] bg-[#fbfdff] text-[#5d738b] hover:bg-[#f2f7fa]"}`} data-testid="button-toggle-filters"><SlidersHorizontal size={16} />Filter</button><button type="button" onClick={() => { setSearch(""); setLevel("all"); setStatus("all"); }} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl px-3 text-xs font-bold text-[#71869c] hover:bg-[#f2f7fa] hover:text-[#2c587a]" data-testid="button-reset-filters"><RotateCcw size={14} />Reset</button></div>{showFilters && <div className="mt-4 grid gap-4 border-t border-[#e7eef4] pt-4 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-[11px] font-bold uppercase tracking-[.1em] text-[#8093a8]">Level bahasa</span><select value={level} onChange={(event) => setLevel(event.target.value as StudentLevel | "all")} className="h-10 w-full rounded-lg border border-[#d4e1ec] bg-[#fbfdff] px-3 text-sm text-[#405871] outline-none focus:border-[#4d94ba]" data-testid="select-level-filter">{levels.map((item) => <option key={item} value={item}>{item === "all" ? "Semua level" : item}</option>)}</select></label><label className="block"><span className="mb-2 block text-[11px] font-bold uppercase tracking-[.1em] text-[#8093a8]">Status portfolio</span><select value={status} onChange={(event) => setStatus(event.target.value as StudentStatus | "all")} className="h-10 w-full rounded-lg border border-[#d4e1ec] bg-[#fbfdff] px-3 text-sm text-[#405871] outline-none focus:border-[#4d94ba]" data-testid="select-status-filter">{statuses.map((item) => <option key={item} value={item}>{statusLabels[item]}</option>)}</select></label></div>}</section>
    <div className="flex items-center justify-between"><div className="flex items-center gap-2 text-sm text-[#71869c]"><Users size={16} className="text-[#5899b7]" /><span data-testid="text-student-count">{isLoading ? "Memuat siswa…" : `${students.length} siswa ditemukan`}</span></div><div className="font-mono-ui text-[10px] uppercase tracking-[.12em] text-[#9aabba]">Sortir: terbaru</div></div>
    <section className="overflow-hidden rounded-2xl border border-[#dfe8f0] bg-white soft-shadow"><div className="hidden grid-cols-[minmax(200px,1.6fr)_100px_150px_115px_28px] gap-4 border-b border-[#e7eef4] bg-[#f9fbfd] px-6 py-3.5 text-[10px] font-bold uppercase tracking-[.12em] text-[#8a9bad] sm:grid"><span>Profil siswa</span><span>Level</span><span>Cohort</span><span>Status</span><span /></div>{isLoading ? <LoadingRows /> : isError ? <div className="px-6 py-14 text-center"><p className="text-sm font-semibold text-[#6e8094]">Daftar siswa tidak dapat dimuat.</p><button type="button" onClick={() => refetch()} className="mt-4 rounded-xl bg-[#1b5a9f] px-4 py-2 text-xs font-bold text-white" data-testid="button-retry-students">Coba lagi</button></div> : students.length ? <div>{students.map((student) => <StudentRow key={student.id} student={student} />)}</div> : <EmptyState title="Belum ada siswa yang cocok" description="Coba ubah kata kunci atau filter untuk melihat portofolio lain." action={<button type="button" onClick={() => { setSearch(""); setLevel("all"); setStatus("all"); }} className="inline-flex items-center gap-2 rounded-xl border border-[#cbdce8] px-4 py-2.5 text-sm font-bold text-[#38637e] hover:bg-[#eff7fa]" data-testid="button-empty-reset"><Filter size={15} />Hapus filter</button>} />}</section>
  </div>;
}