// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-indonesia/Current.tsx": () => import("../components/mockups/landing-indonesia/Current.tsx"),
  "./components/mockups/landing-indonesia/ReferenceLike.tsx": () => import("../components/mockups/landing-indonesia/ReferenceLike.tsx")
};
