export const defaultCmsData = {
  navbar: {
    brandName: "Lernpfad",
    brandSubtitle: "Indonesia · Deutschland",
    brandBadge: "LP",
    ctaText: "Masuk portal",
    ctaHref: "/login",
    ctaEnabled: true,
    links: [
      {
        id: 1,
        label: "Beranda",
        href: "/",
        order: 1,
        isExternal: false,
        isHighlighted: false,
        isVisible: true,
      },
      {
        id: 2,
        label: "Aktuelles",
        sublabel: "Kabar & Media",
        href: "/berita",
        order: 2,
        isExternal: false,
        isHighlighted: false,
        isVisible: true,
        children: [
          { id: 21, label: "News", sublabel: "Berita & Pengumuman", href: "/berita", isVisible: true },
          { id: 22, label: "Presse", sublabel: "Liputan Media & Wawancara", href: "/media", isVisible: true },
          { id: 23, label: "Medien", sublabel: "Dokumenter TV & Video", href: "/media", isVisible: true },
        ],
      },
      {
        id: 3,
        label: "Über AuLiD",
        sublabel: "Tentang Program",
        href: "/layanan",
        order: 3,
        isExternal: false,
        isHighlighted: false,
        isVisible: true,
        children: [
          { id: 31, label: "Layanan & Alur", sublabel: "7 Tahap Persiapan & Keberangkatan", href: "/layanan", isVisible: true },
          { id: 32, label: "Kantor Jakarta", sublabel: "Pusat Koordinasi & Pelatihan", href: "/jakarta", isVisible: true },
          { id: 33, label: "Untuk Partner", sublabel: "Kemitraan Perusahaan Jerman (AG-Anfrage)", href: "/ag-anfrage", isVisible: true },
        ],
      },
      {
        id: 4,
        label: "Referenzen",
        sublabel: "Referensi & Prestasi",
        href: "/referensi",
        order: 4,
        isExternal: false,
        isHighlighted: false,
        isVisible: true,
        children: [
          { id: 41, label: "Kisah Referensi", sublabel: "Kisah Sukses & Juara Alumni", href: "/referensi", isVisible: true },
          { id: 42, label: "Penempatan Berhasil", sublabel: "Bukti Keberangkatan & Karier", href: "/penempatan-berhasil", isVisible: true },
        ],
      },
    ],
  },
  footer: {
    brandName: "Lernpfad",
    brandSubtitle: "Indonesia · Deutschland",
    tagline: "Membuka jalan yang lebih manusiawi antara talenta Indonesia dan dunia kerja Jerman.",
    copyright: "© 2024–2026 Lernpfad. Hak cipta dilindungi undang-undang.",
    contactEmail: "kontakt@aulid.de",
    contactPhone: "+62 823 1249 5802",
    addressJakarta: "Grand Sahid Jaya Jakarta, Jl. M.H. Thamrin No. 12, Jakarta Pusat",
    addressGermany: "Trinumer Weg 4, OT Großpaschleben, 06386 Osternienburger Land",
    links: [
      { id: 1, label: "Beranda", href: "/", category: "Navigasi", order: 1 },
      { id: 2, label: "Kabar terkini", href: "/berita", category: "Navigasi", order: 2 },
      { id: 3, label: "Liputan media", href: "/media", category: "Navigasi", order: 3 },
      { id: 4, label: "Layanan partner", href: "/layanan", category: "Layanan", order: 4 },
      { id: 5, label: "Kantor Jakarta", href: "/jakarta", category: "Layanan", order: 5 },
      { id: 6, label: "Permintaan partner", href: "/ag-anfrage", category: "Layanan", order: 6 },
      { id: 7, label: "Kisah referensi", href: "/referensi", category: "Informasi", order: 7 },
      { id: 8, label: "Penempatan berhasil", href: "/penempatan-berhasil", category: "Informasi", order: 8 },
      { id: 9, label: "Portal Admin", href: "/login", category: "Informasi", order: 9 },
    ],
    socialLinks: [
      { id: 1, platform: "Instagram", label: "@lernpfad.id", url: "https://instagram.com" },
      { id: 2, platform: "LinkedIn", label: "Lernpfad Talent Bridge", url: "https://linkedin.com" },
      { id: 3, platform: "YouTube", label: "Lernpfad Channel", url: "https://youtube.com" },
    ],
  },
  home: {
    eyebrow: "Jembatan talenta Indonesia — Jerman",
    title: "Orang yang tepat, jalan yang jelas.",
    description: "Lernpfad membantu perusahaan di Jerman menemukan peserta Ausbildung dan tenaga layanan yang siap tumbuh — lalu mendampingi mereka dari Indonesia sampai merasa di rumah.",
    primaryCta: "Cari talenta untuk tim Anda",
    primaryCtaHref: "/login",
    secondaryCta: "Kenali pendekatan kami",
    secondaryCtaHref: "#cara-kerja",
    introLabel: "Lebih dari penempatan",
    introTitle: "Kami merawat perjalanan, bukan hanya keberangkatan.",
    introText: "Pindah negara untuk Ausbildung adalah keputusan besar. Karena itu, kami membuat setiap tahap bisa dipahami, dibicarakan, dan dipersiapkan bersama.",
    trustedPartners: ["Bergblick Hotels", "Küchenwerk", "Pflegehaus Nord", "Rhein & Raum"],
    stats: [
      { id: 1, number: "01", value: "A1–B2", label: "Pelatihan terarah", detail: "Kurikulum intensif dan bahasa kerja" },
      { id: 2, number: "02", value: "1:1", label: "Pendampingan dekat", detail: "Bimbingan sejak di Indonesia hingga tiba" },
      { id: 3, number: "03", value: "ID × DE", label: "Satu arah lintas negara", detail: "Kantor Jakarta dan Jerman terhubung" },
      { id: 4, number: "04", value: "100%", label: "Transparansi data", detail: "Verifikasi sertifikat dan video percakapan" },
    ],
    programCards: [
      { id: 1, number: "01", title: "Rekrutmen di Indonesia", text: "Kami bertemu calon peserta langsung di kota asalnya, memahami motivasi, dan menyaring kesiapan sejak percakapan pertama.", accent: "sea" },
      { id: 2, number: "02", title: "Portfolio kandidat", text: "Profil rapi memperlihatkan pengalaman, kemampuan bahasa, minat profesi, dan konteks manusia di balik setiap berkas.", accent: "coral" },
      { id: 3, number: "03", title: "Dokumen dan visa", text: "Tim membantu menyiapkan, menerjemahkan, serta menelusuri dokumen sampai proses bersama pihak terkait.", accent: "butter" },
      { id: 4, number: "04", title: "Pelatihan bahasa Jerman", text: "Pembelajaran terarah dari fondasi hingga percakapan kerja, dengan progres yang bisa dibaca peserta dan pemberi kerja.", accent: "ink" },
      { id: 5, number: "05", title: "Perjalanan terkoordinasi", text: "Penerbangan, transfer, dan momen kedatangan direncanakan bersama agar hari pertama terasa jelas dan terurus.", accent: "lavender" },
      { id: 6, number: "06", title: "Dukungan setelah tiba", text: "Pendampingan tidak berhenti di bandara. Kami tetap hadir saat peserta mulai Ausbildung dan membangun hidup baru.", accent: "sand" },
    ],
    processSteps: [
      { id: 1, number: "01", title: "Mendengar kebutuhan", text: "Kami mulai dari peran, budaya kerja, dan kualitas kandidat yang benar-benar dicari tim Anda." },
      { id: 2, number: "02", title: "Menemukan yang tepat", text: "Kandidat diseleksi melalui percakapan, dokumen, dan asesmen bahasa yang relevan." },
      { id: 3, number: "03", title: "Menyiapkan perpindahan", text: "Pelatihan, dokumen, visa, dan perjalanan dirangkai menjadi satu rencana yang transparan." },
      { id: 4, number: "04", title: "Menjaga hubungan", text: "Setelah tiba, ada satu tim yang tetap mudah dihubungi oleh peserta maupun partner." },
    ],
    quoteText: "Saya tidak merasa dikirim pergi. Saya merasa dipersiapkan untuk datang.",
    quoteAuthor: "Rafi, peserta Ausbildung · Stuttgart",
    trustTitle: "Membuka jalan yang lebih manusiawi.",
    trustText: "Gunakan portfolio dan proses yang transparan untuk memulai percakapan kerja yang lebih percaya diri bersama kandidat Indonesia.",
    ctaTitle: "Mari temukan kemungkinan yang belum terlihat.",
    ctaSubtitle: "Ceritakan posisi atau rencana tim Anda. Masuk ke portal untuk memulai percakapan berbasis portfolio yang sudah terverifikasi.",
    ctaButtonText: "Hubungi tim Lernpfad",
    ctaButtonHref: "/login",
  },
  news: {
    headerEyebrow: "Catatan Lernpfad",
    headerTitle: "Kabar dari sepanjang jalan.",
    headerSubtitle: "Berita, percakapan, dan cerita tentang perjalanan talenta Indonesia menuju dunia kerja Jerman.",
    categories: ["Semua", "Media", "Partner", "Program", "Cerita"],
    items: [
      {
        id: 1,
        date: "18 JUN 2024",
        category: "Media",
        title: "Bagaimana peserta Ausbildung dari Indonesia membantu menjawab kebutuhan tenaga kerja?",
        excerpt: "Lernpfad berbagi perspektif tentang persiapan kandidat, kualitas pendampingan, dan proses membangun masa depan lintas negara.",
        content: "Dalam wawancara khusus ini, Lernpfad memaparkan bagaimana kurikulum terpadu bahasa dan pengenalan budaya kerja Jerman mampu mempersiapkan talenta muda Indonesia bersaing secara sehat dan terhormat di pasar kerja Jerman.",
        featured: true,
        tone: "coral",
        author: "Tim Redaksi Lernpfad",
        published: true,
      },
      {
        id: 2,
        date: "12 JUN 2024",
        category: "Cerita",
        title: "Dari Bandung ke dapur hotel di Baden-Württemberg",
        excerpt: "Satu perjalanan peserta, dari kelas bahasa hingga hari pertama mengenal tempat kerja barunya di Jerman.",
        content: "Kisah inspiratif tentang ketekunan belajar bahasa Jerman selama 8 bulan intensif dan keberanian melangkah ke negara baru untuk menggapai mimpi menjadi juru masak profesional.",
        featured: false,
        tone: "sea",
        author: "Kandidat Story",
        published: true,
      },
      {
        id: 3,
        date: "03 SEP 2023",
        category: "Partner",
        title: "Lernpfad hadir di CHEFS CULINAR Messe di Leipzig",
        excerpt: "Bertemu dengan pelaku industri hospitality dan berbicara tentang cara membuka peluang Ausbildung yang lebih terarah.",
        content: "Dialog aktif dengan puluhan manajer SDM hotel dan restoran ternama di Jerman Timur yang menyambut positif kehadiran tenaga kerja muda asal Indonesia.",
        featured: false,
        tone: "butter",
        author: "B2B Outreach",
        published: true,
      },
      {
        id: 4,
        date: "31 OKT 2022",
        category: "Partner",
        title: "Membangun jalur talenta di Thementage RINGHOTELS",
        excerpt: "Diskusi bersama jaringan hotel tentang kebutuhan tenaga kerja, budaya kerja, dan kesiapan peserta dari Indonesia.",
        content: "Fokus pembahasan pada strategi adaptasi budaya dan mentoring intensif bagi peserta Ausbildung di tahun pertama.",
        featured: false,
        tone: "ink",
        author: "Partnership Team",
        published: true,
      },
      {
        id: 5,
        date: "11 OKT 2022",
        category: "Program",
        title: "Berbagi praktik baik di BAFA Energietag",
        excerpt: "Lernpfad ikut membahas peluang serta tanggung jawab dalam proses masuknya tenaga kerja terampil ke Jerman.",
        content: "Diskusi meja bundar tentang regulasi imigrasi tenaga kerja terbaru dan percepatan verifikasi sertifikasi vokasi.",
        featured: false,
        tone: "lavender",
        author: "Program Development",
        published: true,
      },
      {
        id: 6,
        date: "22 SEP 2022",
        category: "Program",
        title: "Investasi digital untuk masa depan penempatan",
        excerpt: "Pengembangan perangkat lunak Lernpfad membantu proses portfolio dan komunikasi kandidat menjadi lebih terbuka.",
        content: "Peluncuran platform portfolio digital interaktif yang memungkinkan employer melihat video speaking dan skor bahasa siswa secara real-time.",
        featured: false,
        tone: "sea",
        author: "Tech Team",
        published: true,
      },
    ],
  },
  media: {
    headerEyebrow: "Ruang media Lernpfad",
    headerTitle: "Dari layar ke percakapan.",
    headerSubtitle: "Liputan televisi dan dokumenter tentang talenta Indonesia, Ausbildung, dan cara dunia kerja Jerman membuka peluang baru.",
    categories: ["Semua", "Televisi", "Dokumenter"],
    items: [
      {
        id: 1,
        date: "18 JUN 2024",
        category: "Televisi",
        channel: "stern TV Talk",
        title: "Bagaimana peserta Ausbildung dari Indonesia membantu menjawab kebutuhan tenaga kerja?",
        excerpt: "Percakapan tentang peluang, persiapan, dan perjalanan peserta Indonesia menuju dunia kerja Jerman.",
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        featured: true,
        tone: "coral",
        published: true,
      },
      {
        id: 2,
        date: "14 JUN 2024",
        category: "Televisi",
        channel: "stern TV",
        title: "Peserta Ausbildung dari Indonesia menghadapi kebutuhan tenaga kerja",
        excerpt: "Liputan tentang peserta dari Indonesia yang memulai babak baru dalam pendidikan dan pekerjaan di Jerman.",
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        featured: true,
        tone: "sea",
        published: true,
      },
      {
        id: 3,
        date: "02 MEI 2024",
        category: "Dokumenter",
        channel: "Spiegel TV",
        title: "Mengapa sebuah hotel merekrut banyak peserta dari Indonesia?",
        excerpt: "Spiegel TV melihat lebih dekat peran peserta Ausbildung dari Indonesia di Weissenhäuser Strand.",
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        featured: false,
        tone: "butter",
        published: true,
      },
      {
        id: 4,
        date: "18 APR 2024",
        category: "Televisi",
        channel: "ZDF Wiso",
        title: "Kekurangan tenaga kerja: apakah birokrasi menjadi penyebabnya?",
        excerpt: "Laporan tentang proses yang perlu dilalui perusahaan dan calon tenaga kerja internasional.",
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        featured: false,
        tone: "ink",
        published: true,
      },
      {
        id: 5,
        date: "09 MAR 2024",
        category: "Dokumenter",
        channel: "mdr Exakt",
        title: "Selamat datang di dunia gastronomi",
        excerpt: "Mengapa peserta Ausbildung dari Indonesia semakin dibutuhkan oleh industri hospitality.",
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        featured: false,
        tone: "lavender",
        published: true,
      },
      {
        id: 6,
        date: "22 FEB 2024",
        category: "Televisi",
        channel: "ZDF heute",
        title: "Tenaga kerja terampil dari Indonesia",
        excerpt: "ZDF meliput peserta dan tenaga kerja dari Indonesia yang mengisi peluang kerja di Jerman.",
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        featured: false,
        tone: "coral",
        published: true,
      },
    ],
  },
  services: {
    headerEyebrow: "Layanan untuk pemberi kerja",
    headerTitle: "Kami membawa talenta muda lebih dekat.",
    headerSubtitle: "Lernpfad membantu perusahaan menemukan tenaga muda yang dinamis dari Asia Tenggara — dan menyalurkannya secara terarah sebagai peserta Ausbildung.",
    workflowSubtitle: "Pilih satu tahap untuk melihat apa yang terjadi di baliknya. Kami membuat proses lintas negara terasa lebih dekat bagi semua pihak.",
    stages: [
      {
        id: 1,
        number: "01",
        title: "Rekrutmen di lokasi",
        shortTitle: "Kami menemukan",
        description: "Tim lokal bertemu calon peserta di Indonesia, mendengar motivasinya, dan menyaring kesiapan untuk bidang industri, perdagangan, kerajinan, kesehatan, dan layanan.",
        detail: "Penyaringan intensif mencakup wawancara psikologis, latar belakang pendidikan, dan komitmen jangka panjang.",
        tone: "coral",
        iconName: "UsersRound",
      },
      {
        id: 2,
        number: "02",
        title: "Kami belajar bahasa Jerman",
        shortTitle: "Kami mempersiapkan",
        description: "Peserta mengikuti pelatihan bahasa yang terarah, dari fondasi percakapan hingga kosakata kerja yang dibutuhkan di tempat Ausbildung.",
        detail: "Pelatihan difasilitasi penutur asli dan pengajar bersertifikat hingga standar Goethe B1/B2.",
        tone: "sea",
        iconName: "Languages",
      },
      {
        id: 3,
        number: "03",
        title: "Masuk ke Jerman",
        shortTitle: "Kami mengatur",
        description: "Dokumen, visa, jadwal perjalanan, dan komunikasi dengan partner disiapkan sebagai satu rencana yang bisa diikuti bersama.",
        detail: "Pengurusan izin kerja, translasi resmi tersumpah, dan pengajuan visa nasional (kategori 16a/18a).",
        tone: "butter",
        iconName: "Plane",
      },
      {
        id: 4,
        number: "04",
        title: "Tiba di Jerman",
        shortTitle: "Kami menyambut",
        description: "Peserta dijemput dan diarahkan saat kedatangan. Langkah pertama di negara baru tidak perlu dijalani sendirian.",
        detail: "Penjemputan bandara, bantuan orientasi transportasi lokal, dan pendaftaran domisili awal.",
        tone: "ink",
        iconName: "Globe2",
      },
      {
        id: 5,
        number: "05",
        title: "Persiapan memulai Ausbildung",
        shortTitle: "Kami menjembatani",
        description: "Kami membantu peserta memahami ritme hidup, ekspektasi kerja, dan hal-hal praktis sebelum hari pertama dimulai.",
        detail: "Pembekalan kode etik kerja Jerman, kebiasaan hidup sehari-hari, dan pengaturan akomodasi tempat tinggal.",
        tone: "lavender",
        iconName: "ClipboardCheck",
      },
      {
        id: 6,
        number: "06",
        title: "Kunjungan ke tempat Ausbildung",
        shortTitle: "Kami tetap hadir",
        description: "Hubungan dengan peserta dan partner dijaga melalui kunjungan serta komunikasi yang dekat selama masa transisi.",
        detail: "Kunjungan berkala 3 bulanan untuk mengevaluasi progres pembelajaran dan kepuasan employer.",
        tone: "sand",
        iconName: "Building2",
      },
      {
        id: 7,
        number: "07",
        title: "Pendampingan administratif",
        shortTitle: "Kami meneruskan",
        description: "Setelah Ausbildung dimulai, partner tetap mendapat dukungan untuk pertanyaan administratif dan koordinasi lanjutan.",
        detail: "Bantuan perpanjangan izin tinggal, koordinasi asuransi kesehatan, dan administrasi sekolah vokasi (Berufsschule).",
        tone: "sea",
        iconName: "ShieldCheck",
      },
    ],
    benefits: [
      { id: 1, title: "Partner lokal", description: "Satu tim di Indonesia untuk memahami kebutuhan Anda secara spesifik.", icon: "Handshake" },
      { id: 2, title: "Proses terukur", description: "Setiap langkah terdokumentasi dan mudah diikuti secara transparan.", icon: "FileCheck2" },
      { id: 3, title: "Dukungan berlanjut", description: "Hubungan pendampingan tidak berhenti setelah peserta tiba di Jerman.", icon: "ShieldCheck" },
    ],
  },
  jakarta: {
    headerEyebrow: "AuLiD di Jakarta",
    headerTitle: "Tempat pertama untuk bertanya.",
    headerSubtitle: "Kami adalah titik temu di Asia Tenggara bagi anak muda yang ingin mengenal Ausbildung dan peluang kerja di Jerman.",
    contactTitle: "Pertanyaan pertama bisa dikirim hari ini.",
    contactSubtitle: "Isi formulir singkat ini. Tim Lernpfad di Jakarta akan segera menghubungi Anda dengan informasi lengkap.",
    officeJakarta: {
      name: "German Institut Jakarta",
      building: "Grand Sahid Jaya Jakarta",
      address: "Jl. M.H. Thamrin No. 12, Jakarta Pusat, Indonesia",
      phone: "+62 823 1249 5802",
      email: "jakarta@aulid.de",
      coordinates: "ID · 06°10′S",
      operatingHours: "Senin – Jumat: 08:30 – 17:00 WIB",
    },
    officeGermany: {
      name: "Ausbildung & Leben in Deutschland",
      address: "Trinumer Weg 4, OT Großpaschleben, 06386 Osternienburger Land, Jerman",
      phone: "+49 3496 511 7003",
      email: "kontakt@aulid.de",
      coordinates: "DE · 51°46′N",
      operatingHours: "Montag – Freitag: 09:00 – 17:00 CET",
    },
    pillars: [
      { id: 1, number: "01", title: "Menjawab pertanyaan", description: "Tentang syarat, pilihan profesi, kemampuan bahasa, dan kehidupan nyata di Jerman." },
      { id: 2, number: "02", title: "Membaca kesiapan", description: "Mengenal motivasi, pengalaman, dan rencana setiap calon peserta secara utuh dan jujur." },
      { id: 3, number: "03", title: "Menghubungkan peluang", description: "Mencari jalur Ausbildung yang paling sesuai dengan kemampuan dan arah masa depan." },
    ],
  },
  references: {
    headerEyebrow: "Referensi keberhasilan",
    headerTitle: "Bukti bahwa jalan ini bisa ditempuh.",
    headerSubtitle: "Di balik setiap penempatan ada latihan, keberanian, dan hasil yang layak dirayakan. Inilah beberapa momen dari perjalanan peserta Lernpfad.",
    quoteText: "Hasil yang baik tidak datang sekaligus. Ia tumbuh dari hari-hari ketika seseorang memilih untuk terus mencoba.",
    stories: [
      {
        id: "catharine",
        eyebrow: "Berhasil di tahun ketiga Ausbildung",
        title: "Juara pertama kompetisi memasak tingkat muda",
        description: "Catharine Magdalena, peserta Ausbildung di Hotel Höpke, Bad Laer, mendapat penghargaan Juara 1 Jugendmeisterin Koch. Sebuah pencapaian yang lahir dari ketekunan, latihan, dan keberanian untuk terus belajar.",
        result: "1.",
        resultLabel: "Juara muda memasak",
        personName: "Catharine Magdalena",
        company: "Hotel Höpke, Bad Laer",
        year: "2024",
        tone: "butter",
        published: true,
      },
      {
        id: "graduated",
        eyebrow: "Ausbildung berhasil diselesaikan",
        title: "Dari peserta menjadi rekan kerja",
        description: "Joshua Gabe, Rosinta Caterine Siregar, Fiter Sidabutar, dan Christian Siregar telah menyelesaikan Ausbildung mereka. Perjalanan mereka menunjukkan apa yang bisa terjadi ketika persiapan dan kesempatan bertemu.",
        result: "4",
        resultLabel: "Lulusan yang dirayakan",
        personName: "Joshua, Rosinta, Fiter & Christian",
        company: "Mitra Gastronomi & Perhotelan",
        year: "2023–2024",
        tone: "coral",
        published: true,
      },
    ],
  },
  placements: {
    headerEyebrow: "Penempatan berhasil",
    headerTitle: "Ketika orang yang tepat bertemu tempat yang tepat.",
    headerSubtitle: "Penempatan bukan hanya soal mengisi posisi. Ini tentang membangun awal yang baik untuk peserta, perusahaan, dan hubungan yang ingin bertahan lebih lama.",
    steps: [
      {
        id: 1,
        number: "01",
        title: "Memahami kebutuhan",
        description: "Kami mulai dari posisi, lingkungan kerja, dan karakter partner. Kecocokan yang baik selalu dimulai dengan pertanyaan yang tepat.",
        detail: "Mendalami profil perusahaan, ritme kerja, dan fasilitas yang disiapkan untuk peserta baru.",
        tone: "butter",
        iconName: "Compass",
      },
      {
        id: 2,
        number: "02",
        title: "Menemukan kecocokan",
        description: "Profil, motivasi, kemampuan bahasa, dan kesiapan peserta dipertimbangkan sebagai satu kesatuan—bukan sekadar daftar kualifikasi.",
        detail: "Pencocokan berbasis portfolio video, asesmen psikotes, dan simulasi situasi kerja.",
        tone: "coral",
        iconName: "UsersRound",
      },
      {
        id: 3,
        number: "03",
        title: "Mendampingi proses",
        description: "Komunikasi antara peserta dan perusahaan dijaga sejak perkenalan hingga persiapan keberangkatan ke Jerman.",
        detail: "Wawancara daring terfasilitasi, penerjemahan dokumen, dan koordinasi kontrak kerja resmi.",
        tone: "sea",
        iconName: "Handshake",
      },
      {
        id: 4,
        number: "04",
        title: "Menjaga awal yang baru",
        description: "Setelah penempatan, dukungan tetap berlanjut agar peserta dan partner dapat membangun awal yang stabil.",
        detail: "Evaluasi transisi bulan ke-1, ke-3, dan ke-6 bersama pembimbing di tempat kerja.",
        tone: "ink",
        iconName: "ShieldCheck",
      },
    ],
    principles: [
      { id: 1, number: "01", title: "Jelas sejak awal", description: "Ekspektasi yang dipahami bersama mengurangi kejutan di kemudian hari." },
      { id: 2, number: "02", title: "Dekat saat dibutuhkan", description: "Dukungan hadir di momen transisi yang paling penting bagi peserta dan partner." },
      { id: 3, number: "03", title: "Dibangun bersama", description: "Perusahaan dan peserta sama-sama punya ruang untuk bertumbuh dalam jangka panjang." },
    ],
  },
  partner: {
    headerEyebrow: "Untuk pemberi kerja",
    headerTitle: "Temukan orang yang tepat untuk tim Anda.",
    headerSubtitle: "Mari mulai dengan percakapan informasi. Tim kami akan menjelaskan cara kerja, kemungkinan, dan langkah untuk menemukan peserta Ausbildung yang andal dan termotivasi.",
    contactPerson: {
      name: "Wolfgang Nickel",
      role: "Koordinator Hubungan Kemitraan Jerman",
      location: "Großpaschleben, Jerman (51°46′N)",
      phone: "+49 3496 511 7003",
      email: "kontakt@aulid.de",
      description: "Satu percakapan awal untuk memahami kebutuhan spesifik tim dan posisi yang sedang dibuka di perusahaan Anda.",
    },
    benefits: [
      { id: 1, title: "Informasi yang jelas", description: "Pahami kemungkinan dan cara kerja sebelum mengambil langkah komitmen.", icon: "MessageSquareText" },
      { id: 2, title: "Dibuat untuk tim Anda", description: "Percakapan dimulai dari posisi dan lingkungan kerja nyata di perusahaan Anda.", icon: "Building2" },
      { id: 3, title: "Respons yang dekat", description: "Setelah data diperiksa, tim kami di Jerman akan segera menghubungi Anda.", icon: "ShieldCheck" },
    ],
    formTitle: "Ceritakan kebutuhan perusahaan Anda.",
    formSubtitle: "Isi data formulir di bawah ini untuk memulai konsultasi awal tanpa ikatan.",
  },
};
